package com.lalilu.krouter.compiler

import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSNode
import com.lalilu.kspcollector.CollectorConfig
import com.lalilu.kspcollector.MetadataCollector

/**
 * KSP 参数 key：额外收集的注解 FQN 列表，逗号分隔。
 * 处理器会将这些注解与 KRouter 自带的 [DEFAULT_ANNOTATIONS] 合并收集。
 *
 * 使用方式：
 * ```kotlin
 * ksp {
 *     arg("krouter.collect.annotations", "com.example.MyRoute,com.example.MyService")
 * }
 * ```
 */
const val KSP_ARG_EXTRA_ANNOTATIONS = "krouter.collect.annotations"

/** KRouter 默认收集的注解列表。 */
val DEFAULT_ANNOTATIONS =
    listOf(
        "com.lalilu.krouter.annotation.Destination",
        "com.lalilu.krouter.annotation.KService",
    )

/**
 * 从 KSP options 中解析注解列表：默认 + 用户通过 [KSP_ARG_EXTRA_ANNOTATIONS] 传入的。
 */
fun resolveAnnotations(options: Map<String, String>): List<String> {
    val extra =
        options[KSP_ARG_EXTRA_ANNOTATIONS]
            ?.split(",")
            ?.map { it.trim() }
            ?.filter { it.isNotEmpty() }
            ?: emptyList()
    return DEFAULT_ANNOTATIONS + extra
}

/**
 * 注解收集处理器 — 将当前模块中标注了指定注解的类写入 metadata，
 * 供注入处理器跨模块读取。
 *
 * 除了默认的 @Destination 和 @KService 外，还可通过 KSP 参数
 * `krouter.collect.annotations` 传入额外注解。
 *
 * @see KRouterInjectProcessor 注入处理器
 */
open class KRouterCollectProcessor(
    protected val environment: SymbolProcessorEnvironment,
) : SymbolProcessor {
    protected fun log(
        message: String,
        symbol: KSNode? = null,
    ) = environment.logger.warn(message, symbol)

    private val annotations = resolveAnnotations(environment.options)

    private val collector =
        MetadataCollector(
            CollectorConfig(
                annotations = annotations,
                sharedPackage = GENERATED_SHARED_PACKAGE,
                kdoc =
                    """
                    |Generated by KRouter (https://github.com/cy745/KRouter).
                    |DO NOT MODIFY — changes will be overwritten.
                    """.trimMargin(),
            ),
        )

    companion object {
        const val GENERATED_SHARED_PACKAGE = "com.lalilu.krouter.generated"
    }

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val clazzMap =
            collector.collect(resolver, environment.codeGenerator)
                ?: return emptyList()

        return resolver
            .getClassDeclarationByName(clazzMap)
            ?.let { listOf(it) }
            ?: emptyList()
    }
}
