package com.lalilu.krouter.compiler

import com.google.devtools.ksp.KspExperimental
import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.isAnnotationPresent
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.lalilu.krouter.InjectMap
import com.lalilu.krouter.annotation.Destination
import com.lalilu.krouter.annotation.KInject
import com.lalilu.krouter.annotation.KService
import com.lalilu.krouter.compiler.code.buildGetRouterMapFunc
import com.lalilu.krouter.compiler.code.buildHandleParamsFunction
import com.lalilu.krouter.compiler.code.buildParamStateClass
import com.lalilu.krouter.compiler.code.generateKInjectActualImplementations
import com.lalilu.krouter.compiler.code.handleServicesProperties
import com.lalilu.kspcollector.MetadataReader
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * 路由注入处理器：收集所有模块的 @Destination / @KService，生成 KRouterInjectMap。
 *
 * ## 三轮处理时序
 *
 * ```
 *     Round 1                Round 2               Round 3
 * ┌──────────────┐    ┌──────────────────┐    ┌──────────────────┐
 * │super.process │    │super.process     │    │readWithFallback  │
 * │生成 metadata │    │再次生成 metadata │    │读取所有 metadata │
 * │@KInject      │    │metadata 已可见   │    │+ 当前模块注解    │
 * │actual 生成   │    │但 metadataSeen=1 │    │metadataSeen=2   │
 * ├──────────────┤    │→ 跳过，返回      │    │→ 正式注入        │
 * │返回 metadata │    └──────────────────┘    │生成 InjectMap   │
 * │→ 触发 Round 2│                           └──────────────────┘
 * └──────────────┘
 * ```
 *
 * ## 为什么需要三轮？
 *
 * 1. **跨模块 metadata 可见性**：KSP 的 getDeclarationsFromPackage() 在第一轮
 *    看不到同一轮生成的文件，第二轮才可见。
 * 2. **等待其他 KSP 处理器**（如 Koin）：第二轮 metadata 可见后不立即注入，
 *    再等一轮给其他处理器生成代码的机会。第三轮注入时，其他处理器生成的
 *    带注解类已在 classpath 上，可被 getSymbolsWithAnnotation() 收录。
 * 3. **当前模块注解**：第三轮中当前模块自己的 metadata 由 super.process()
 *    刚刚生成、同轮不可见，readWithFallback() 会额外调用 getSymbolsWithAnnotation()
 *    直接补充。
 * 4. **@KInject 的特殊性**：第三轮 KSP 中 expect fun 不可见，actual 生成
 *    必须在第一轮完成。
 */
class KRouterInjectProcessor(
    environment: SymbolProcessorEnvironment,
) : KRouterCollectProcessor(environment) {
    companion object {
        /** 生成的注入映射类名 */
        val className = "KRouterInjectMap"
        val CLASS_KDOC =
            """
            |Generated by KRouter (https://github.com/cy745/KRouter).
            |DO NOT MODIFY — changes will be overwritten.
            """.trimMargin()
    }

    /** inject 阶段只执行一次，避免多轮重复生成 */
    private var injectPhaseDone = false

    /**
     * metadata 可见的轮次数统计。用于实现三轮时序：
     *   第 1 次（round 2）→ super.process() 收集，返回触发 round 3
     *   第 2 次（round 3）→ 读取 metadata + inject
     */
    private var metadataSeenCount = 0

    /** @KInject 只在第一轮处理（第二轮 KSP 中 expect fun 不可见） */
    private var kInjectDone = false

    /** 跨模块 metadata 读取器 */
    private val metadataReader = MetadataReader(GENERATED_SHARED_PACKAGE)

    @OptIn(KspExperimental::class)
    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (injectPhaseDone) return emptyList()

        // ── 第一轮：生成 metadata，返回触发第二轮 ──
        val resultList = super.process(resolver)

        // @KInject 只能在第一轮处理（expect fun 后续轮次不可见）
        if (!kInjectDone) processKInjectFunctions(resolver)

        // ── 检查 metadata 是否已可索引 ──
        val collectedClasses =
            metadataReader.readWithFallback(
                resolver = resolver,
                ownAnnotations = resolveAnnotations(environment.options),
            )

        if (collectedClasses.isEmpty()) {
            // 第一轮：metadata 刚生成尚未索引 → 返回触发第二轮
            if (environment.codeGenerator.generatedFile.isNotEmpty()) {
                return resultList
            }
            // 无任何注解
            writeKRouterInjectMap(
                environment.codeGenerator,
                emptyList(),
                emptyList(),
                emptyList(),
            )
            injectPhaseDone = true
            return emptyList()
        }

        // ── metadata 可见（第二轮+） ──
        metadataSeenCount++
        if (metadataSeenCount == 1) {
            // 第二轮：让其他 KSP 处理器（Koin 等）再跑一轮，不注入
            return resultList
        }

        // ── 第三轮+：正式注入 ──
        val destinations = collectedClasses.filter { it.isAnnotationPresent(Destination::class) }
        val kservices = collectedClasses.filter { it.isAnnotationPresent(KService::class) }
        val extraServices =
            collectedClasses.filter { clazz ->
                !clazz.isAnnotationPresent(Destination::class) && !clazz.isAnnotationPresent(KService::class)
            }
        // services 最终产物包含 @KService + 自定义注解收集的类
        val allServices = kservices + extraServices

        writeKRouterInjectMap(environment.codeGenerator, collectedClasses, destinations, allServices)

        val extraAnnotations =
            resolveAnnotations(environment.options)
                .filter { it !in DEFAULT_ANNOTATIONS }
        printCollectReport(collectedClasses, destinations, kservices, extraServices, extraAnnotations)

        injectPhaseDone = true

        return resolver
            .getClassDeclarationByName(className)
            ?.let { listOf(it) }
            ?: emptyList()
    }

    /** 收集 @KInject expect fun 并生成 actual 实现（仅在 KSP source 可见的第一轮执行） */
    private fun processKInjectFunctions(resolver: Resolver) {
        kInjectDone = true
        val functions =
            resolver
                .getSymbolsWithAnnotation(KInject::class.qualifiedName!!)
                .filterIsInstance<KSFunctionDeclaration>()
                .filter { func ->
                    // 跳过已生成的 actual（避免上游生成的 actual 带 @KInject 导致循环）
                    if (func.isActual) return@filter false
                    val returnType =
                        func.returnType
                            ?.resolve()
                            ?.declaration
                            ?.qualifiedName
                            ?.asString()
                    returnType == "com.lalilu.krouter.InjectMap"
                }.toList()

        if (functions.isNotEmpty()) {
            functions.generateKInjectActualImplementations(environment.codeGenerator)
        }
    }

    /** 打印收集统计报告 */
    private fun printCollectReport(
        collectedMap: List<KSClassDeclaration>,
        destinations: List<KSClassDeclaration>,
        kservices: List<KSClassDeclaration>,
        extraServices: List<KSClassDeclaration>,
        extraAnnotations: List<String>,
    ) {
        val hasData = collectedMap.isNotEmpty() || extraAnnotations.isNotEmpty()
        if (!hasData && extraAnnotations.isEmpty()) {
            log(
                "╔═══════════════════════════════════════\n║  📦 KRouter Collect Report\n║  ─────────────────────────────\n║  ⚠️  No annotated classes found\n╚═══════════════════════════════════════",
            )
            return
        }

        log(
            buildString {
                appendLine("╔═══════════════════════════════════════")
                appendLine("║  📦 KRouter Collect Report")
                appendLine("║  ─────────────────────────────")
                // ── @Destination ──
                if (destinations.isNotEmpty()) {
                    appendLine("║")
                    appendLine("║  🧭  Destinations (${destinations.size}):")
                    destinations.forEach { d ->
                        appendLine("║     • ${d.qualifiedName?.asString() ?: "?"}")
                    }
                }
                // ── @KService (services 中的内置部分) ──
                if (kservices.isNotEmpty()) {
                    appendLine("║")
                    appendLine("║  🔧  @KService (${kservices.size}):")
                    kservices.forEach { s ->
                        appendLine("║     • ${s.qualifiedName?.asString() ?: "?"}")
                    }
                }
                // ── 自定义注解收集的类 → 也进入 services ──
                if (extraServices.isNotEmpty()) {
                    appendLine("║")
                    appendLine("║  📦  Extra in Services (${extraServices.size}):")
                    extraServices.forEach { c ->
                        val annNames =
                            c.annotations
                                .mapNotNull {
                                    it.annotationType
                                        .resolve()
                                        .declaration.qualifiedName
                                        ?.asString()
                                }.filter { it !in DEFAULT_ANNOTATIONS }
                                .joinToString(", ") { it.substringAfterLast('.') }
                        appendLine("║     • ${c.qualifiedName?.asString() ?: "?"}  [$annNames]")
                    }
                }
                // ── Extra Annotations 配置详情 ──
                if (extraAnnotations.isNotEmpty()) {
                    appendLine("║")
                    appendLine("║  🏷️  Extra Annotation Config:")
                    extraAnnotations.forEach { ann ->
                        val matched =
                            collectedMap.filter { clazz ->
                                clazz.annotations.any { a ->
                                    a.annotationType
                                        .resolve()
                                        .declaration.qualifiedName
                                        ?.asString() == ann
                                }
                            }
                        val status =
                            if (matched.isNotEmpty()) {
                                "✅ ${matched.size} classes"
                            } else {
                                "❌ none"
                            }
                        appendLine("║     [${ann.substringAfterLast('.')}]  $status  ($ann)")
                    }
                }
                append("╚═══════════════════════════════════════")
            },
        )
    }

    /** 写入 KRouterInjectMap 源码文件 */
    @OptIn(KspExperimental::class)
    private fun writeKRouterInjectMap(
        codeGenerator: CodeGenerator,
        collectedMap: List<KSClassDeclaration>,
        destinations: List<KSClassDeclaration>,
        services: List<KSClassDeclaration>,
    ) {
        val classSpec =
            TypeSpec
                .objectBuilder(className)
                .addSuperinterface(InjectMap::class)
                .addKdoc(CLASS_KDOC)
                .addAnnotation(
                    AnnotationSpec
                        .builder(Suppress::class)
                        .addMember("%S", "UNCHECKED_CAST")
                        .build(),
                ).addProperty(handleServicesProperties(services))
                .addFunction(buildGetRouterMapFunc(destinations))
                .addType(buildParamStateClass())
                .addFunction(buildHandleParamsFunction())
                .build()

        val fileSpec =
            FileSpec
                .builder(GENERATED_SHARED_PACKAGE, className)
                .addType(classSpec)
                .indent("    ")
                .build()

        val dependencies =
            collectedMap
                .mapNotNull { it.containingFile }
                .distinct()
                .toTypedArray()

        runCatching {
            fileSpec.writeTo(
                codeGenerator = codeGenerator,
                dependencies = Dependencies(aggregating = true, *dependencies),
            )
        }.onFailure { e ->
            log("Failed to write generated inject map: ${e.message}")
        }
    }
}
