package com.lalilu.krouter.compiler

import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSNode
import com.lalilu.krouter.annotation.Destination
import com.lalilu.krouter.annotation.KService
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * 注解收集处理器 — 将当前模块中 @Destination 和 @KService 的类元数据
 * 写入公共包 `GENERATED_SHARED_PACKAGE`，供注入处理器（[KRouterInjectProcessor]）
 * 跨模块读取。
 *
 * 生成的元数据类示例（类名基于内容 hash）：
 * ```kotlin
 * package com.lalilu.krouter.generated
 *
 * class KRouterMap_Metadata_1986967826 {
 *   private lateinit var com_lalilu_krouter_test_TestScreen: TestScreen
 *   private lateinit var com_lalilu_krouter_test_MainScreen: MainScreen
 * }
 * ```
 *
 * 此处理器可通过 `kRouterType=collect` 在依赖模块中独立配置运行。
 * 配置为 inject 的主模块在生成 [KRouterInjectMap] 时会从 classpath
 * 上读取这些 metadata 类，实现跨模块聚合。
 *
 * @see KRouterInjectProcessor 注入处理器（主模块使用）
 */
open class KRouterCollectProcessor(
    protected val environment: SymbolProcessorEnvironment,
) : SymbolProcessor {
    protected fun log(
        message: String,
        symbol: KSNode? = null,
    ) = environment.logger.warn(message, symbol)

    companion object {
        const val GENERATED_SHARED_PACKAGE = "com.lalilu.krouter.generated"
        const val CLASS_KDOC = "This class is generated by KRouter, do not modify it."
    }

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val destinations =
            resolver
                .getSymbolsWithAnnotation(Destination::class.qualifiedName!!)
                .map { it as KSClassDeclaration }
                .toList()

        val services =
            resolver
                .getSymbolsWithAnnotation(KService::class.qualifiedName!!)
                .map { it as KSClassDeclaration }
                .toList()

        // 生成metadata文件，写入收集到的类，且建立依赖关系
        val clazzMap =
            writeToFile(environment.codeGenerator, destinations + services)
                ?: return emptyList()

        // 返回metadata类，告诉ksp，这个类被收集了，允许下一轮获取到该类
        return resolver
            .getClassDeclarationByName(clazzMap)
            ?.let { listOf(it) }
            ?: emptyList()
    }

    private fun writeToFile(
        codeGenerator: CodeGenerator,
        collectedMap: List<KSClassDeclaration>,
    ): String? {
        if (collectedMap.isEmpty()) return null

        val propertySpecs =
            collectedMap.mapNotNull { item ->
                val name =
                    item.qualifiedName
                        ?.asString()
                        ?.replace('.', '_')
                        ?.takeIf(String::isNotBlank)
                        ?: return@mapNotNull null

                PropertySpec
                    .builder(name, item.toClassName())
                    .addModifiers(KModifier.LATEINIT, KModifier.PRIVATE)
                    .mutable(true)
                    .build()
            }

        // 获取所有类，计算hash值，类名变化或增删时触发hash发送变化
        val hashes =
            collectedMap
                .mapNotNull { it.qualifiedName?.asString() }
                .sorted()
                .joinToString("|")
                .hashCode()
                .toUInt()
                .toString(16)

        val className = "KRouterMap_Metadata_$hashes"
        val classSpec =
            TypeSpec
                .classBuilder(className)
                .addKdoc(CLASS_KDOC)
                .addProperties(propertySpecs)
                .build()

        val fileSpec =
            FileSpec
                .builder(GENERATED_SHARED_PACKAGE, className)
                .addType(classSpec)
                .indent("    ")
                .build()

        // 将涉及到的类所涉及的文件作为依赖传入，方便增量编译
        val dependencies =
            collectedMap
                .mapNotNull { it.containingFile }
                .distinct()
                .toTypedArray()

        fileSpec.writeTo(
            codeGenerator = codeGenerator,
            dependencies = Dependencies(aggregating = true, *dependencies),
        )

        return className
    }
}
