package com.lalilu.krouter.compiler

import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSNode
import com.lalilu.kspcollector.CollectorConfig
import com.lalilu.kspcollector.MetadataCollector

/**
 * 注解收集处理器 — 将当前模块中 @Destination 和 @KService 的类元数据
 * 写入公共包 `com.lalilu.krouter.generated`，供注入处理器跨模块读取。
 *
 * 收集逻辑委托给 [MetadataCollector]，此类仅负责 KRouter 特有的调度逻辑。
 *
 * @see KRouterInjectProcessor 注入处理器
 */
open class KRouterCollectProcessor(
    protected val environment: SymbolProcessorEnvironment,
) : SymbolProcessor {
    protected fun log(
        message: String,
        symbol: KSNode? = null,
    ) = environment.logger.warn(message, symbol)

    private val collector =
        MetadataCollector(
            CollectorConfig(
                annotations =
                    listOf(
                        "com.lalilu.krouter.annotation.Destination",
                        "com.lalilu.krouter.annotation.KService",
                    ),
                sharedPackage = GENERATED_SHARED_PACKAGE,
                kdoc =
                    """
                    |Generated by KRouter (https://github.com/cy745/KRouter).
                    |DO NOT MODIFY — changes will be overwritten.
                    """.trimMargin(),
            ),
        )

    companion object {
        const val GENERATED_SHARED_PACKAGE = "com.lalilu.krouter.generated"
    }

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val clazzMap =
            collector.collect(resolver, environment.codeGenerator)
                ?: return emptyList()

        return resolver
            .getClassDeclarationByName(clazzMap)
            ?.let { listOf(it) }
            ?: emptyList()
    }
}
