package com.lalilu.kspcollector

/**
 * 收集器配置。
 *
 * @property annotations 要扫描的注解全限定名列表。每个注解对应一次 [resolver.getSymbolsWithAnnotation] 扫描。
 * @property sharedPackage metadata 类写入的目标包。读取端通过 [MetadataReader] 在此包下查找。
 * @property kdoc 生成文件的头部文档注释。
 */
data class CollectorConfig(
    val annotations: List<String>,
    val sharedPackage: String,
    val kdoc: String = "Generated by ksp-collector. DO NOT MODIFY.",
)
